USE [master]
GO

CREATE DATABASE [TrinetixInterview]
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TrinetixInterview].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TrinetixInterview] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TrinetixInterview] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TrinetixInterview] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TrinetixInterview] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TrinetixInterview] SET ARITHABORT OFF 
GO
ALTER DATABASE [TrinetixInterview] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TrinetixInterview] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [TrinetixInterview] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TrinetixInterview] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TrinetixInterview] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TrinetixInterview] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TrinetixInterview] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TrinetixInterview] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TrinetixInterview] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TrinetixInterview] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TrinetixInterview] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TrinetixInterview] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TrinetixInterview] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TrinetixInterview] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TrinetixInterview] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TrinetixInterview] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TrinetixInterview] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TrinetixInterview] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TrinetixInterview] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TrinetixInterview] SET  MULTI_USER 
GO
ALTER DATABASE [TrinetixInterview] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TrinetixInterview] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TrinetixInterview] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TrinetixInterview] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [TrinetixInterview]
GO
/****** Object:  Table [dbo].[FileNames]    Script Date: 18.05.2015 21:13:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FileNames](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_File] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[FilePaths]    Script Date: 18.05.2015 21:13:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FilePaths](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[FullPath] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Path] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Locations]    Script Date: 18.05.2015 21:13:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Locations](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[WordId] [bigint] NOT NULL,
	[FileNameId] [bigint] NOT NULL,
	[FilePathId] [bigint] NOT NULL,
	[Row] [bigint] NOT NULL,
	[Column] [bigint] NOT NULL,
 CONSTRAINT [PK_Location] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Words]    Script Date: 18.05.2015 21:13:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Words](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Word] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Index [IX_Locations]    Script Date: 18.05.2015 21:13:25 ******/
CREATE NONCLUSTERED INDEX [IX_Locations] ON [dbo].[Locations]
(
	[FileNameId] ASC,
	[FilePathId] ASC,
	[WordId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Locations]  WITH CHECK ADD  CONSTRAINT [FK_Location_File] FOREIGN KEY([FileNameId])
REFERENCES [dbo].[FileNames] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Locations] CHECK CONSTRAINT [FK_Location_File]
GO
ALTER TABLE [dbo].[Locations]  WITH CHECK ADD  CONSTRAINT [FK_Location_Path] FOREIGN KEY([FilePathId])
REFERENCES [dbo].[FilePaths] ([Id])
GO
ALTER TABLE [dbo].[Locations] CHECK CONSTRAINT [FK_Location_Path]
GO
ALTER TABLE [dbo].[Locations]  WITH CHECK ADD  CONSTRAINT [FK_Location_Word] FOREIGN KEY([WordId])
REFERENCES [dbo].[Words] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Locations] CHECK CONSTRAINT [FK_Location_Word]
GO
USE [master]
GO
ALTER DATABASE [TrinetixInterview] SET  READ_WRITE 
GO
