//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrinetixInterview.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilePath
    {
        public FilePath()
        {
            this.Locations = new HashSet<Location>();
        }
    
        public long Id { get; set; }
        public string FullPath { get; set; }
    
        public virtual ICollection<Location> Locations { get; set; }
    }
}
