//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrinetixInterview.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public long Id { get; set; }
        public long WordId { get; set; }
        public long FileNameId { get; set; }
        public long FilePathId { get; set; }
        public long Row { get; set; }
        public long Column { get; set; }
    
        public virtual FileName FileName { get; set; }
        public virtual FilePath FilePath { get; set; }
        public virtual Word Word { get; set; }
    }
}
